// Autogenerated sequence file generated on 2022-03-08 16:29:55.349007.

const String UNITS_mL = "mL";
const unsigned int NO_SAMPLES = 4;
const float SYG_DIA_mL = 20;
const bool DO_REPEAT = true;
const unsigned int NO_SEQUENCES = 1;
const float REPEAT[4] = {1.0, 2.0, 3.0, 4.0};
const float* SEQ_LIST[1] = {REPEAT};

// Autogenerated Sequence file ends here.